sudo: required
dist: trusty
language: node_js
node_js:
  - 4
  - 6
  - 8
install:
   - npm install --ignore-engines
script:
  - 'npm test'
after_success:
  - 'npm run cover:up'
notifications:
  email: false
