sudo: required
dist: trusty
language: node_js
node_js:
  - 4
  - 6
  - 7
install:
   - yarn install --ignore-engines
script:
  - 'yarn test'
after_success:
  - 'yarn cover:up'
notifications:
  email: false
